name: flutter_screenshot_switcher_example
description: Demonstrates how to use the flutter_screenshot_switcher plugin.
publish_to: 'none'
version: 5.0.0

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_screenshot_switcher:
    path: ../

flutter:
  uses-material-design: true

