name: flutter_screenshot_switcher
description: A flutter plugin that allows to enable &#x2F; disable screenshots.
version: 2.1.0
homepage: https://github.com/jeroentrappers/flutter_screenshot_switcher

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: be.appmire.flutter_screenshot_switcher
        pluginClass: FlutterScreenshotSwitcherPlugin
      ios:
        pluginClass: FlutterScreenshotSwitcherPlugin


